# Generated by Django 5.0.3 on 2024-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='titulo',
            field=models.CharField(default='Valor por defecto by now', verbose_name='Título de la publicación'),
            preserve_default=False,
        ),
    ]
