# Generated by Django 5.0.3 on 2024-03-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicaciones_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(default='No valor by now', upload_to='posts', verbose_name='Imagen para la publicación'),
            preserve_default=False,
        ),
    ]
