# Generated by Django 5.0.3 on 2024-03-25 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicaciones_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='publicaciones',
            options={'verbose_name': 'Publicación', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AddField(
            model_name='autor',
            name='foto_perfil',
            field=models.ImageField(default='Le falta foto', upload_to='', verbose_name='Foto de perfil del autor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(upload_to='portadas_libros', verbose_name='Portada del libro')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del libro')),
                ('autor', models.CharField(verbose_name='Autor del libro')),
                ('descripcion', models.TextField(verbose_name='Descripción del libro')),
                ('archivo', models.FileField(upload_to='pdfs', verbose_name='PDF/Epub del libro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.categorias')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
